#!/bin/csh -f

###############################################################################
# vpp is a remote printing program (via tcp/ip) furnished by ethz and widely  #
# used at psi. On other sites it has to be replaced by something else.        #
###############################################################################

# black and white remote printer:

if ($argv[1] == 1) then
#  echo "Printing via VPP"
#  vpp -dev=PS800 $argv[2] >/dev/null
   echo "Printing via CUPS"
   lp -d WLGA_D12_2 $argv[2]
endif

# colored remote printer:

if ($argv[1] == 2) then
  echo "Printing via VPP"
  vpp -dest=PSW01 -dev=PHASER $argv[2] >/dev/null
endif

# printing with local color printer:

if ($argv[1] == 4) then
  echo " Printing via ghostscript with HP Deskjet 550c."
  gs -q -sDEVICE=cdj550 -sOutputFile=f.p $argv[2] <gsprompt >/dev/null
  lpr -l -s -r f.p
  echo " Printout queued."
endif

# printing with local monochrome printer:

if ($argv[1] == 3) then
  echo " Printing via ghostscript with Canon BJ-10e."
  gs -q -sDEVICE=bj10e -sOutputFile=f.p $argv[2] <gsprompt >/dev/null
  lpr -l -s -r f.p
  echo " Printout queued."
endif
